### ISSUE TITLE
Ensure that properties in a resource state expressed with yaml are properly coerced

### ISSUE THREAD

**Issue by thallgren** [lyraproj/lyra#116]
The problem can be illustrated given the following Kubernetes resource:
```
k8s_namespace:
  typespace: TerraformKubernetes
  output:
    kubernetes_namespace_id: String
  activities:
    kubernetes_namespace:
      output: kubernetes_namespace_id
      state:
        kubernetes_namespace_id: "ignore"
        metadata:
          name: "terraform-lyra"
          resource_version: "hi"
          self_link: "me"
```
Here, the attribute `metadata` will be read as a map with the inferred type `Struct[name => String, resource_version => String, self_link => String]`. The inferred resource type, in this case `TerraformKubernetes::Kubernetes_namespace` is however declared as:
```
Kubernetes_namespace => {
  attributes => {
    'kubernetes_namespace_id' => {
      'type' => Optional[String],
      'value' => undef
    },
    'metadata' => Kubernetes_namespace_metadata_721
  }
},
```
and `Kubernetes_namespace_metadata_721` is actually an `ObjectType` and attempting to assign an object of type `Struct` to it does not work.

The solution to this is that since all types are known to Lyra, the map can be coerced into an instance of the correct type using the constructor of the type. Adding such coercion will benefit other types as well such as SemVer and Timestamp that can be created from strings.
