### ISSUE TITLE
Deletion of AWS internet gateway fails because we do not supply enough context

### ISSUE THREAD

**Issue by scottyw** [lyraproj/lyra#204]
**Describe the bug**
Deletion of an AWS internet gateway via the TF content fails with a dependency error because the gateway must be detached from the VPC first. The TF content does actually detach the gateway and handle this situation but requires the corresponding VPC id. 

First intuition is that we need to read the state of a resource before deletion, passing that just-read state into the delete operation.

**To Reproduce**
Apply then delete the following workflow:
```yaml
aws:
  typespace: TerraformAws
  activities:
    aws_vpc:
      output: aws_vpc_id
      state:
        cidr_block: 192.168.0.0/16
        instance_tenancy: default
    aws_internet_gateway:
      state:
        vpc_id: $aws_vpc_id
```

Application succeeds but deletion fails.

**Expected behavior**
Deletion should succeed.
