### ISSUE TITLE
Support for the "each" iterator in YAML

### ISSUE THREAD

**Issue by scottyw** [lyraproj/lyra#209]
**Is your feature request related to a problem? Please describe.**
We support iterators in YAML including "times" and "range". This ticket captures implementing support for "each" as well.

**Describe the solution you'd like**
Here's an example workflow:
```yaml
aws:
  typespace: TerraformAws
  input:
    subnet_cidr_blocks:
      type: Array
      lookup: subnet_cidr_blocks
  output: subnets
  activities:

    aws_vpc:
      # type is implicit and is derived from the
      # activity name, in contrast to subnets below
      output: aws_vpc_id
      state:
        cidr_block: 192.168.0.0/16
        instance_tenancy: default

    aws_subnet:
      type:  TerraformAws::aws_subnet
      output:
         key: aws_subnet_id
         value: [aws_subnet_id]
      iteration:
         name:     subnets
         function: each
         over:     subnet_cidr_blocks
         vars:     cidr_block
      state:
        vpc_id: $aws_vpc_id
        cidr_block: $cidr_block
        tags:
          created_by: lyra
```
Input data would be something like:
```yaml
subnet_cidr_blocks: [ 192.168.1.0/24, 192.168.2.0/24, 192.168.3.0/24 ]
```
