### ISSUE TITLE
Investigate Helm integration

### ISSUE THREAD

**Issue by ahpook** [lyraproj/lyra#265]
**Is your feature request related to a problem? Please describe.**
We had some discussion on this in #88 (now closed) but this is a bit different: 

As someone who's got applications already packaged for deployment onto Kubernetes as Helm charts, I'd like to be able to reference and use those charts as part of a Lyra workflow, without modifying the charts. 

**Describe the solution you'd like**
Some pseudo syntax in yaml:

```yaml
steps:
   wordpress:
    Helm::Wordpress:
      wordpressBlogName: $blogname
      externaldatabase:
        host: $mysql_server_id
        database: $mysql_database_id
        user: $dbuser
        password: $dbpass
```

**Describe alternatives you've considered**
We could run helm as an imperative command line step as a minimal starting point.
