### ISSUE TITLE
Investigate higher-level Terraform integration

### ISSUE THREAD

**Issue by ahpook** [lyraproj/lyra#266]
**Is your feature request related to a problem? Please describe.**
Currently, we can make use of the terraform provider ecosystem, but this is pretty low-level; almost any nontrivial service requires a bunch of TF resources to be aggregated and managed together. There is a healthy ecosystem of TF modules indexed on the [TF Module Registry](https://registry.terraform.io/), not to mention a huge number of existing `.tf` plans that people have written to describe their own business logic.

It would be extremely beneficial to be able to reuse these without modification in Lyra, so we could "compose" a workflow that consists of (for example) terraform modules to create infrastructure, Helm charts to deploy onto that infra, and chatops notifications when we're done. 

**Describe the solution you'd like**
Psuedocode:

```yaml
steps:
  tf_mysql:
    # based on https://github.com/foreverXZC/terraform-azurerm-mysql
    returns:
      fqdn: name
      server_name: name
      database_name: name
      admin_username: name
    Terraform::Module:
      name: azurerm-mysql
      source: foreverXZC/mysql/azurem
      db_name: databass
      location: eastus
      admin_username: lyra
      password: Aw3s0mep4ss!
```
