### ISSUE TITLE
Rename step "reference" to "call"

### ISSUE THREAD

**Issue by thallgren** [lyraproj/lyra#282]
The name "reference" was chosen because when running, the wf-engine will replace it with another, referenced step and apply aliases for parameters and returns. When declaring a workflow though, the name "call" seems more intuitive. Compare:
```
foo:
  call: bar
  parameters:
    our_a: bar_a
    our_b: bar_b
  return:
    our_c: bar_c
```
to the current
```
foo:
  reference: bar
  parameters:
    our_a: bar_a
    our_b: bar_b
  return:
    our_c: bar_c
```
