### ISSUE TITLE
YAML support

### ISSUE THREAD

**Issue by kenazk** [lyraproj/lyra#36]
**Is your feature request related to a problem? Please describe.**
When I am authoring a Workflow manifest, I want to use YAML to describe the resources I'm creating so that I can leverage my existing knowledge and skillset. 

**Describe the solution you'd like**
I'd like to be able to describe a set of declarative resources with YAML. 

**Describe alternatives you've considered**
None.

**Additional context**
YAML is the defacto standard in the Kubernetes community. There are lots of users who are already familiar with YAML. It does not require someone to learn Puppet. 

Of course, there are a lot of things that YAML is not good at (e.g. imperative actions). I propose that we exclude any procedural or imperative actions from YAML support. 

Here's an example:

```yaml
lyra::aws::vpc:  
    type: resource  
    input:    
        region:
            type: String
            lookup: aws.region    
        tags:
            type: Hash[String,String]
            lookup: aws.tags  
    output: vpc_id  
    body:    
            ensure: present    
            region: !input region    
            cidr_block: 192.168.0.0/16    
            tags: !input tags    
            enable_dns_hostnames: true    
            enable_dns_support  : true
```
